NEST-487: Upgrade to Orchard Core 1.8
agriffard/TheResumeTheme pull request #28
Opened 2024-03-10 12:55 UTC by Psichorex

NEST-487

2024-03-11 08:06 UTC, agriffard approved these changes

2024-03-28 13:24 UTC, wAsnk requested changes

2024-03-28 13:24 UTC, wAsnk commented on src/TheResumeTheme/Recipes/TheResumeTheme.Tests.recipe.json
> -{
Why was this deleted?

2024-03-28 14:58 UTC, Psichorex commented on src/TheResumeTheme/Recipes/TheResumeTheme.Tests.recipe.json
> -{
I have no clue. It was deleted on the merge commit from master to my branch. I readded it because it is present in the main source.

2024-03-28 15:21 UTC, closed without merging